pull_request_rules:
  - name: 'Merge my PRs when CI/CD passes âœ…'
    conditions:
      - author=xhudec
      - status-success=static-tests
      - status-success=app-tests
      - label!=Work in progress âš ï¸
    actions:
      merge:
        method: squash
  - name: 'Merge PRs when approved ðŸ‘€ and CI/CD passes âœ…'
    conditions:
      - '#approved-reviews-by>=1'
      - status-success=static-tests
      - status-success=app-tests
    actions:
      merge:
        method: squash
  - name: 'Delete host branch after PR is merged ðŸ§¹'
    conditions:
      - merged
    actions:
      delete_head_branch: {}
